ARG HERMES_BASE=hermes-agent:local
FROM ${HERMES_BASE}

USER root
ARG CUA_DRIVER_VERSION=0.19.3
ARG CUA_DRIVER_URL=https://files.pythonhosted.org/packages/88/26/1b372765b192a2f4f7ee7e1474d1e39be9ab3bd637765f632e30e7ee6e18/cua_driver-0.19.3-py3-none-manylinux_2_31_x86_64.whl
ARG CUA_DRIVER_SHA256=3f327a444f5b666037dee5e7c15c98990abbfb4fe83669ef708cb34c2cafef14
RUN curl -fsSL "$CUA_DRIVER_URL" -o /tmp/cua-driver.whl \
    && echo "$CUA_DRIVER_SHA256  /tmp/cua-driver.whl" | sha256sum -c - \
    && python3 -m venv /opt/cua \
    && /opt/cua/bin/pip install --no-cache-dir --no-deps /tmp/cua-driver.whl \
    && driver_bin="$(find /opt/cua/lib -path '*/cua_driver/bin/cua-driver' -type f -print -quit)" \
    && install -m 0755 "$driver_bin" /usr/local/bin/cua-driver \
    && test "$(cua-driver --version)" = "cua-driver ${CUA_DRIVER_VERSION}" \
    && rm -f /tmp/cua-driver.whl
COPY --chmod=0755 hermes-cua-wrapper /usr/local/bin/hermes-cua-wrapper
ENV HERMES_CUA_DRIVER_CMD=/usr/local/bin/hermes-cua-wrapper
